package expo.modules.notificationlistener

import java.security.KeyPairGenerator
import java.security.PrivateKey
import java.security.PublicKey
import java.security.SecureRandom
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey

/**
 * Plain-JCE, in-memory stand-in for [KeyVault], used only by JVM tests
 * (`KeyStoreBridgeTest`). Every key here is a real key -- a real AES-256
 * `SecretKey`, a real RSA-2048 keypair -- generated by the JDK's default
 * providers instead of "AndroidKeyStore". That is what lets
 * `KeyStoreBridgeTest` run on a plain JVM: the AES-GCM / RSA-OAEP `Cipher`
 * calls in [KeyStoreBridge] are the exact same real `javax.crypto` code path
 * either way, so a bug there (a reused IV, a skipped tag check, a no-op
 * "wrap") shows up here exactly as it would in production.
 *
 * What this deliberately does NOT do: build, or even reference, a
 * `KeyGenParameterSpec`. None of the Android-Keystore-specific
 * configuration (hardware backing, `setUserAuthenticationRequired`,
 * `setInvalidatedByBiometricEnrollment`, StrongBox) exists here at all --
 * see [KeyVault]'s class doc for what that means for what these tests can
 * and can't prove.
 */
internal class FakeKeyVault : KeyVault {
  private val secretKeys = mutableMapOf<String, SecretKey>()
  private val keyPairs = mutableMapOf<String, java.security.KeyPair>()

  override fun getOrCreateAesKey(alias: String) {
    secretKeys.getOrPut(alias) {
      KeyGenerator.getInstance("AES").apply { init(256, SecureRandom()) }.generateKey()
    }
  }

  override fun getOrCreateRsaKeyPair(alias: String) {
    keyPairs.getOrPut(alias) {
      KeyPairGenerator.getInstance("RSA").apply { initialize(2048) }.generateKeyPair()
    }
  }

  override fun getAesKey(alias: String): SecretKey =
    secretKeys[alias] ?: error("secret key has not been created")

  override fun getPublicKey(alias: String): PublicKey =
    keyPairs[alias]?.public ?: error("capture keypair has not been created")

  override fun getPrivateKey(alias: String): PrivateKey =
    keyPairs[alias]?.private ?: error("capture keypair has not been created")

  override fun hasAesKey(alias: String): Boolean = secretKeys.containsKey(alias)
}
