package expo.modules.notificationlistener

import android.security.keystore.KeyPermanentlyInvalidatedException
import android.security.keystore.UserNotAuthenticatedException
import java.security.KeyPairGenerator
import java.security.PrivateKey
import java.security.PublicKey
import java.security.SecureRandom
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey

/**
 * Plain-JCE, in-memory stand-in for [KeyVault], used only by JVM tests
 * (`KeyStoreBridgeTest`). Every key here is a real key -- a real AES-256
 * `SecretKey`, a real RSA-2048 keypair -- generated by the JDK's default
 * providers instead of "AndroidKeyStore". That is what lets
 * `KeyStoreBridgeTest` run on a plain JVM: the AES-GCM / RSA-OAEP `Cipher`
 * calls in [KeyStoreBridge] are the exact same real `javax.crypto` code path
 * either way, so a bug there (a reused IV, a skipped tag check, a no-op
 * "wrap") shows up here exactly as it would in production.
 *
 * What this deliberately does NOT do: build, or even reference, a
 * `KeyGenParameterSpec`. None of the Android-Keystore-specific
 * configuration (hardware backing, `setUserAuthenticationRequired`,
 * `setInvalidatedByBiometricEnrollment`, StrongBox) exists here at all --
 * see [KeyVault]'s class doc for what that means for what these tests can
 * and can't prove.
 */
internal class FakeKeyVault : KeyVault {
  private val secretKeys = mutableMapOf<String, SecretKey>()
  private val keyPairs = mutableMapOf<String, java.security.KeyPair>()

  override fun getOrCreateAesKey(alias: String) {
    secretKeys.getOrPut(alias) {
      KeyGenerator.getInstance("AES").apply { init(256, SecureRandom()) }.generateKey()
    }
  }

  /**
   * Byte-for-byte identical to [getOrCreateAesKey] here, and that is not a
   * shortcut -- it is the honest modelling. The ONLY difference between the
   * two in production is `setUserAuthenticationRequired(false)` on the
   * `KeyGenParameterSpec`, and this class never constructs one (see the class
   * doc above), so there is nothing here for the distinction to attach to.
   *
   * Concretely: a mutation that flipped `AndroidKeyVault`'s
   * `setUserAuthenticationRequired` to `true` -- which would make the
   * provider filter unreadable while the phone is locked, i.e. on nearly
   * every capture -- would leave every JVM test in this module green. That
   * assertion lives in
   * `src/androidTest/.../KeyStoreBridgeInstrumentedTest.kt`
   * (`prefsKekIsNotUserAuthenticationBound`) and can only run on a device.
   */
  override fun getOrCreateUnauthenticatedAesKey(alias: String) = getOrCreateAesKey(alias)

  // Unconditionally overwrites -- matches AndroidKeyVault's "always
  // rotates, regardless of prior state" contract for this function. A
  // plain Map#put here is enough: unlike AndroidKeyVault there is no
  // separate delete step to model, since there is no real Keystore entry
  // that must be removed before a new one can take its name.
  override fun recreateAesKey(alias: String) {
    secretKeys[alias] = KeyGenerator.getInstance("AES").apply { init(256, SecureRandom()) }.generateKey()
  }

  override fun getOrCreateRsaKeyPair(alias: String) {
    keyPairs.getOrPut(alias) {
      KeyPairGenerator.getInstance("RSA").apply { initialize(2048) }.generateKeyPair()
    }
  }

  // Unconditionally overwrites, like recreateAesKey above and for the same
  // reason: AndroidKeyVault deletes the alias and regenerates, and the
  // observable effect is a keypair that is not the previous one. Tests rely on
  // that being observable -- a capture sealed under the old public half must
  // stop opening after this runs.
  override fun recreateRsaKeyPair(alias: String) {
    keyPairs[alias] = KeyPairGenerator.getInstance("RSA").apply { initialize(2048) }.generateKeyPair()
  }

  override fun getAesKey(alias: String): SecretKey =
    secretKeys[alias] ?: error("secret key has not been created")

  override fun getPublicKey(alias: String): PublicKey =
    keyPairs[alias]?.public ?: error("capture keypair has not been created")

  override fun getPrivateKey(alias: String): PrivateKey =
    keyPairs[alias]?.private ?: error("capture keypair has not been created")

  override fun hasAesKey(alias: String): Boolean = secretKeys.containsKey(alias)
}

/**
 * A capture private key that is UNAVAILABLE RIGHT NOW, while everything else
 * -- the public half above all -- keeps working through [delegate]. Exactly
 * [UserNotAuthenticatedException] in production: the caller reached
 * [CaptureEnvelope.open] before the private key's ~10-second post-unlock
 * authentication window was open.
 *
 * That asymmetry is the whole of docs/12-encryption-and-app-lock.md §6: the
 * listener can always seal and can never open until the user authenticates.
 * This is a RECOVERABLE state -- the same call retried after authenticating
 * succeeds -- which is why [CaptureBuffer.drain] must leave the file
 * untouched when it meets one.
 */
internal class LockedPrivateKeyVault(private val delegate: KeyVault) : KeyVault by delegate {
  override fun getPrivateKey(alias: String): PrivateKey = throw UserNotAuthenticatedException()
}

/**
 * A capture private key Android has PERMANENTLY DESTROYED -- what removing
 * the device screen lock does to a key created with
 * `setUserAuthenticationRequired(true)` (docs §5). The public half still
 * reads back through [delegate], because the dead alias survives
 * invalidation: that is precisely why the listener keeps sealing captures
 * under a key nothing can ever open again.
 *
 * DIFFERENT IN KIND from [LockedPrivateKeyVault], and the difference is the
 * entire point of having both. "Locked" is recoverable by authenticating;
 * this is not recoverable at all, and no amount of retrying helps.
 * [KeyPermanentlyInvalidatedException] extends `InvalidKeyException`, so
 * anything catching broadly swallows it -- see `CaptureBufferTest`'s
 * dead-key drain case for what that currently costs (GAP-059).
 */
internal class InvalidatedPrivateKeyVault(private val delegate: KeyVault) : KeyVault by delegate {
  override fun getPrivateKey(alias: String): PrivateKey =
    throw KeyPermanentlyInvalidatedException()
}
