// app/index.tsx — the entry route (task-10-brief.md; docs/12-encryption-and-app-lock.md
// §5). Reached via NORMAL file-based routing, which per app/_layout.tsx's
// four-condition render gate (interface contract §10) only happens once the
// app is bootstrapped AND unlocked — meaning the database is open and
// `app_settings` is readable, which is what makes the getSetting() call
// below safe. A brand-new user with no keys at all never reaches this file:
// contexts/lock_context.tsx's own "needs_onboarding" status routes them
// through app/lock.tsx directly to app/(onboarding)/index.tsx WITHOUT this
// Stack-hosted route ever mounting (see that file's header comment for why).
//
// This file's own job is narrower: an unlocked user (keys exist) who has
// not finished onboarding — either because Task 10's two steps just ran and
// M3c's remaining steps have not (M3c is not built yet; see
// app/(onboarding)/index.tsx's own fallback for that exact case), or because
// `onboarding_complete` genuinely has never been set — goes to
// "/(onboarding)" rather than the tabs. Everyone else goes to the tabs.
import { Redirect, type Href } from "expo-router";
import { useEffect, useState } from "react";
import { getSetting } from "@/lib/db/repos/app_settings_repo";

export default function Index() {
  const [onboardingComplete, setOnboardingComplete] = useState<boolean | null>(null);

  useEffect(() => {
    let cancelled = false;
    getSetting("onboarding_complete")
      .then((value) => {
        if (!cancelled) setOnboardingComplete(value);
      })
      .catch(() => {
        // An unreadable setting must never be read as "onboarding is done"
        // — see this file's header comment. app/(onboarding)/index.tsx's own
        // getKeyState() check makes routing here safe even when keys
        // already exist (it falls straight through to "/(tabs)"), so
        // failing TOWARD onboarding, never away from it, is the honest
        // default here.
        if (!cancelled) setOnboardingComplete(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  if (onboardingComplete === null) {
    return null;
  }

  // The `as unknown as Href` cast on "/(onboarding)" is a LOCAL-machine-only
  // concern, not a real forward-reference: the route genuinely exists as of
  // this same task. Expo Router's typed-routes union is generated by the
  // dev server scanning app/ (mobile/.expo/types/router.d.ts, gitignored)
  // and this checkout's copy predates app/(onboarding)/index.tsx, so it does
  // not know this literal yet. Any `expo start` regenerates it and this
  // cast becomes redundant, but harmless to leave.
  return (
    <Redirect href={(onboardingComplete ? "/(tabs)" : "/(onboarding)") as unknown as Href} />
  );
}
