const { AndroidConfig, withAndroidManifest, withDangerousMod, withGradleProperties } =
  require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

/**
 * Plan Task 12 -- everything the `llama.rn` dependency needs from the Android
 * build, owned by one plugin.
 *
 * WHY A CONFIG PLUGIN: `mobile/android/` is generated by `expo prebuild` and
 * EAS Build and is gitignored (CNG). A `gradle.properties` or a
 * `backup_rules.xml` edited by hand in there is destroyed by the next prebuild,
 * so both have to be produced at generation time or they do not exist at all.
 *
 * IT DOES TWO THINGS AND BOTH ARE REQUIRED:
 *
 *   1. EXCLUDES THE MODELS DIRECTORY FROM ANDROID BACKUP. `app.json` sets no
 *      app-wide `android:allowBackup="false"`, so Android's default is to try
 *      to back this directory up, and 3.3 GB of public weights into a user's
 *      Google backup quota is both absurd and a support incident. The exclusion
 *      stays even if an app-wide flag later makes it redundant, because an
 *      app-wide flag is not this module's to depend on.
 *
 *   2. PINS THE BUILD TO arm64. Spec §6 risk 3. `llama.rn` ships fourteen
 *      CPU-dispatch variants of its native library per ABI; building the other
 *      three architectures multiplies the APK for silicon this app does not
 *      target.
 */

/**
 * `domain="file"` is Android's name for the app's own `files/` directory, which
 * is where the downloader writes. A `files/` prefix or a leading slash on the
 * path below produces a rule Android never matches, and the exclusion silently
 * does nothing while the XML remains perfectly valid.
 *
 * `__tests__/app_plugin.test.ts` re-derives both from here rather than
 * retyping them, because a typo in a backup path prebuilds cleanly, builds
 * cleanly, and excludes nothing.
 */
const BACKUP_EXCLUDE_DOMAIN = "file";
const BACKUP_EXCLUDE_PATH = "models/";

/** Resource names, referenced from the manifest as `@xml/<name>`. */
const BACKUP_RULES_RESOURCE = "backup_rules";
const DATA_EXTRACTION_RULES_RESOURCE = "data_extraction_rules";

/** Where prebuild expects Android XML resources, relative to the project root. */
const XML_RESOURCE_DIR = ["app", "src", "main", "res", "xml"];

const ARCHITECTURES_PROPERTY = "reactNativeArchitectures";
const ANDROID_ABI = "arm64-v8a";

const EXCLUSION = `<exclude domain="${BACKUP_EXCLUDE_DOMAIN}" path="${BACKUP_EXCLUDE_PATH}" />`;

/** Read by every device below API 31. */
function backupRulesXml() {
  return `<?xml version="1.0" encoding="utf-8"?>
<full-backup-content>
    ${EXCLUSION}
</full-backup-content>
`;
}

/**
 * Read by API 31+. BOTH sections are required: `device-transfer` is the
 * phone-to-phone copy, and excluding only the cloud path still drags gigabytes
 * of public weights across a cable during a device migration.
 */
function dataExtractionRulesXml() {
  return `<?xml version="1.0" encoding="utf-8"?>
<data-extraction-rules>
    <cloud-backup>
        ${EXCLUSION}
    </cloud-backup>
    <device-transfer>
        ${EXCLUSION}
    </device-transfer>
</data-extraction-rules>
`;
}

/**
 * Points the application at both rule resources.
 *
 * BOTH ATTRIBUTES, not one. `android:dataExtractionRules` is ignored below API
 * 31 and `android:fullBackupContent` is ignored at or above it, so shipping
 * either alone leaves half the install base backing up the weights.
 *
 * @param {import("expo/config-plugins").AndroidManifest} androidManifest
 * @returns {import("expo/config-plugins").AndroidManifest}
 */
function injectBackupRules(androidManifest) {
  const application =
    AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);

  // Added to the attribute bag, never assigned over it: `android:name` and
  // `android:label` are already there and other plugins contribute more.
  application.$["android:fullBackupContent"] = `@xml/${BACKUP_RULES_RESOURCE}`;
  application.$["android:dataExtractionRules"] = `@xml/${DATA_EXTRACTION_RULES_RESOURCE}`;

  return androidManifest;
}

/**
 * @param {{ type: string, key?: string, value?: string }[]} properties
 * @returns {{ type: string, key?: string, value?: string }[]}
 */
function pinArchitectures(properties) {
  // Filtered then appended, rather than appended outright. A duplicate key in
  // `gradle.properties` resolves to the LAST occurrence, so a second entry
  // would work by luck and break the day something reorders the file.
  const withoutArchitectures = properties.filter(
    (entry) => entry.key !== ARCHITECTURES_PROPERTY,
  );

  withoutArchitectures.push({
    type: "property",
    key: ARCHITECTURES_PROPERTY,
    value: ANDROID_ABI,
  });

  return withoutArchitectures;
}

/** @type {import("expo/config-plugins").ConfigPlugin} */
const withLlamaBridge = (config) => {
  let next = withAndroidManifest(config, (manifestConfig) => {
    manifestConfig.modResults = injectBackupRules(manifestConfig.modResults);
    return manifestConfig;
  });

  next = withGradleProperties(next, (propertiesConfig) => {
    propertiesConfig.modResults = pinArchitectures(propertiesConfig.modResults);
    return propertiesConfig;
  });

  // The rule files themselves. There is no `withAndroidResource` for arbitrary
  // `res/xml`, so they are written directly into the generated project -- which
  // is exactly what "dangerous" means here and why it is confined to two files
  // this module owns outright.
  return withDangerousMod(next, [
    "android",
    async (dangerousConfig) => {
      const directory = path.join(
        dangerousConfig.modRequest.platformProjectRoot,
        ...XML_RESOURCE_DIR,
      );
      fs.mkdirSync(directory, { recursive: true });
      fs.writeFileSync(
        path.join(directory, `${BACKUP_RULES_RESOURCE}.xml`),
        backupRulesXml(),
        "utf8",
      );
      fs.writeFileSync(
        path.join(directory, `${DATA_EXTRACTION_RULES_RESOURCE}.xml`),
        dataExtractionRulesXml(),
        "utf8",
      );
      return dangerousConfig;
    },
  ]);
};

module.exports = withLlamaBridge;
module.exports.BACKUP_EXCLUDE_DOMAIN = BACKUP_EXCLUDE_DOMAIN;
module.exports.BACKUP_EXCLUDE_PATH = BACKUP_EXCLUDE_PATH;
module.exports.BACKUP_RULES_RESOURCE = BACKUP_RULES_RESOURCE;
module.exports.DATA_EXTRACTION_RULES_RESOURCE = DATA_EXTRACTION_RULES_RESOURCE;
module.exports.XML_RESOURCE_DIR = XML_RESOURCE_DIR;
module.exports.ARCHITECTURES_PROPERTY = ARCHITECTURES_PROPERTY;
module.exports.ANDROID_ABI = ANDROID_ABI;
module.exports.backupRulesXml = backupRulesXml;
module.exports.dataExtractionRulesXml = dataExtractionRulesXml;
