const { AndroidConfig, withAndroidManifest } = require("expo/config-plugins");

/**
 * M1a plan Task 7 -- declares `PeraPlanoNotificationListenerService` in the
 * generated `AndroidManifest.xml`.
 *
 * WHY THIS IS A CONFIG PLUGIN: `mobile/android/` is generated by
 * `expo prebuild` and EAS Build and is gitignored (CNG). A manifest edited by
 * hand there is destroyed by the next prebuild, so this declaration has to be
 * produced at generation time or it does not exist at all.
 *
 * WHY IT IS LOAD-BEARING: without the `<service>` block below, Android never
 * lists PeraPlano on the Notification Access screen, the user has nothing to
 * grant, `isAccessGranted()` returns false forever, and the capture service,
 * the prefs, the buffer and the bridge are all unreachable code.
 */

/**
 * Must stay identical to the shipped Kotlin class -- a typo here produces a
 * manifest that prebuilds and builds cleanly and silently never starts the
 * service. `__tests__/app_plugin.test.ts` re-derives this from the `.kt` file.
 */
const SERVICE_CLASS =
  "expo.modules.notificationlistener.PeraPlanoNotificationListenerService";

/**
 * Holding this permission is what restricts binding to the system. Without it
 * ANY installed app could bind the service and be handed every notification
 * the user receives.
 */
const BIND_PERMISSION = "android.permission.BIND_NOTIFICATION_LISTENER_SERVICE";

/** The action Android matches to find notification listeners. */
const LISTENER_ACTION = "android.service.notification.NotificationListenerService";

/**
 * Android re-binds an already-granted listener service itself after a reboot,
 * so no custom `BOOT_COMPLETED` receiver is needed -- the permission is
 * declared purely for that boot-time re-bind path.
 */
const BOOT_PERMISSION = "android.permission.RECEIVE_BOOT_COMPLETED";

/**
 * NOTE: `android.permission.READ_SMS` is deliberately absent and must stay
 * absent. Google Play prohibits it for expense tracking and shipping it risks
 * removal of the app; bank SMS reach PeraPlano as notifications posted by the
 * device's Messages app, so it would buy nothing either.
 */

/**
 * NOTE: `android.permission.QUERY_ALL_PACKAGES` is ALSO deliberately absent
 * and must stay absent. It is a Play-restricted permission requiring a
 * declaration form and a policy justification, and the `<queries>` element
 * below buys everything this app needs from it. See `injectPackageQueries`.
 */

/**
 * The MAIN/LAUNCHER pair, which is Android's own definition of "an app with an
 * icon in the launcher" -- every bank and e-wallet PeraPlano can name.
 */
const LAUNCHER_ACTION = "android.intent.action.MAIN";
const LAUNCHER_CATEGORY = "android.intent.category.LAUNCHER";

/**
 * Declares the package visibility `AppLabels.kt` needs to read another app's
 * real name (Android 11 / API 30+).
 *
 * WHY VISIBILITY AT ALL: `PackageManager.getApplicationLabel` is the only
 * source of truth for what an installed app is currently CALLED, and without
 * a matching `<queries>` entry `getApplicationInfo` throws
 * `NameNotFoundException` for every third-party package on API 30+. The
 * provider picker's alternative is the parser seed's hand-written brand
 * names, which go stale on a rebrand -- `ph.seabank.seabank` renders as
 * "seabank" while the app on the user's phone says Maribank, and the user is
 * being asked to confirm that this is their banking app.
 *
 * WHY THE BROAD INTENT FORM, NOT AN ENUMERATED `<package>` LIST: an
 * enumerated list can only name packages this build already knows, which
 * excludes the two cases that matter most -- an app the listener OBSERVED
 * that the seed has never heard of, and a package added by a remote ruleset
 * update after this APK shipped. Both would keep rendering raw package ids.
 *
 * WHAT THIS DOES AND DOES NOT GRANT. It lets the app ASK about a launchable
 * package. It grants no ability to read another app's data, and this module
 * never enumerates installed apps: `appLabels` resolves only the packages
 * handed to it, which come from the picker's own list. It is also a strictly
 * smaller disclosure than what this app already holds -- notification-listener
 * access delivers the full text of every notification on the device, which
 * necessarily includes which apps posted them.
 *
 * @param {import("expo/config-plugins").AndroidManifest} androidManifest
 * @returns {import("expo/config-plugins").AndroidManifest}
 */
function injectPackageQueries(androidManifest) {
  const manifest = androidManifest.manifest;
  const queries = manifest.queries ?? [];

  // IDEMPOTENT, same reason as the `<service>` below: the plugin can be
  // applied twice, and a duplicate `<queries>` intent is merge noise at best.
  const alreadyDeclared = queries.some((entry) =>
    (entry?.intent ?? []).some(
      (intent) =>
        (intent?.action ?? []).some(
          (action) => action?.$?.["android:name"] === LAUNCHER_ACTION,
        ) &&
        (intent?.category ?? []).some(
          (category) => category?.$?.["android:name"] === LAUNCHER_CATEGORY,
        ),
    ),
  );

  if (!alreadyDeclared) {
    // Appended, never assigned over: other libraries contribute their own
    // `<queries>` entries and replacing the array would strip them.
    queries.push({
      intent: [
        {
          action: [{ $: { "android:name": LAUNCHER_ACTION } }],
          category: [{ $: { "android:name": LAUNCHER_CATEGORY } }],
        },
      ],
    });
  }

  manifest.queries = queries;

  return androidManifest;
}

/** One `<service>` element, in the xml2js shape the manifest mod works in. */
function listenerServiceElement(label) {
  return {
    $: {
      "android:name": SERVICE_CLASS,
      // Not addressable from outside the app; the system binds it via the
      // intent-filter action below, which `exported="false"` does not block.
      "android:exported": "false",
      // What the system Notification Access screen shows next to the toggle.
      // Tracks the app name so each build variant -- PeraPlano, PeraPlano(Dev),
      // PeraPlano(Prev) -- is distinguishable when granting access.
      "android:label": label,
      "android:permission": BIND_PERMISSION,
    },
    "intent-filter": [{ action: [{ $: { "android:name": LISTENER_ACTION } }] }],
  };
}

/**
 * @param {import("expo/config-plugins").AndroidManifest} androidManifest
 * @param {string} label human-readable name shown on the Notification Access screen
 * @returns {import("expo/config-plugins").AndroidManifest}
 */
function injectListenerService(androidManifest, label) {
  const application =
    AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);

  // Appended to whatever is already there -- other libraries contribute
  // services to this same array, and replacing it would strip them.
  const existing = application.service ?? [];

  // IDEMPOTENT BY `android:name`, the only identity Android itself uses. The
  // plugin can legitimately be applied more than once (listed in app.json and
  // picked up again by something else), and a duplicated `<service>` fails the
  // manifest merger at build time.
  const alreadyDeclared = existing.findIndex(
    (service) => service?.$?.["android:name"] === SERVICE_CLASS,
  );

  if (alreadyDeclared === -1) {
    existing.push(listenerServiceElement(label));
  } else {
    // Rewritten rather than skipped, so a stale element left by an older
    // version of this plugin cannot survive with weaker attributes.
    existing[alreadyDeclared] = listenerServiceElement(label);
  }

  application.service = existing;

  // `ensurePermission`, not `addPermission`: the latter appends unconditionally
  // and would emit a second `<uses-permission>` on a second application.
  AndroidConfig.Permissions.ensurePermission(androidManifest, BOOT_PERMISSION);

  return androidManifest;
}

/** @type {import("expo/config-plugins").ConfigPlugin} */
const withNotificationListener = (config) => {
  // Resolved app name (varies per build variant); falls back to the product
  // name if a caller ever applies the plugin to a config without one.
  const label = config.name ?? "PeraPlano";
  return withAndroidManifest(config, (manifestConfig) => {
    manifestConfig.modResults = injectPackageQueries(
      injectListenerService(manifestConfig.modResults, label),
    );
    return manifestConfig;
  });
};

module.exports = withNotificationListener;
