const { AndroidConfig, withAndroidManifest } = require("expo/config-plugins");

/**
 * M1a plan Task 7 -- declares `PeraPlanoNotificationListenerService` in the
 * generated `AndroidManifest.xml`.
 *
 * WHY THIS IS A CONFIG PLUGIN: `mobile/android/` is generated by
 * `expo prebuild` and EAS Build and is gitignored (CNG). A manifest edited by
 * hand there is destroyed by the next prebuild, so this declaration has to be
 * produced at generation time or it does not exist at all.
 *
 * WHY IT IS LOAD-BEARING: without the `<service>` block below, Android never
 * lists PeraPlano on the Notification Access screen, the user has nothing to
 * grant, `isAccessGranted()` returns false forever, and the capture service,
 * the prefs, the buffer and the bridge are all unreachable code.
 */

/**
 * Must stay identical to the shipped Kotlin class -- a typo here produces a
 * manifest that prebuilds and builds cleanly and silently never starts the
 * service. `__tests__/app_plugin.test.ts` re-derives this from the `.kt` file.
 */
const SERVICE_CLASS =
  "expo.modules.notificationlistener.PeraPlanoNotificationListenerService";

/**
 * Holding this permission is what restricts binding to the system. Without it
 * ANY installed app could bind the service and be handed every notification
 * the user receives.
 */
const BIND_PERMISSION = "android.permission.BIND_NOTIFICATION_LISTENER_SERVICE";

/** The action Android matches to find notification listeners. */
const LISTENER_ACTION = "android.service.notification.NotificationListenerService";

/**
 * Android re-binds an already-granted listener service itself after a reboot,
 * so no custom `BOOT_COMPLETED` receiver is needed -- the permission is
 * declared purely for that boot-time re-bind path.
 */
const BOOT_PERMISSION = "android.permission.RECEIVE_BOOT_COMPLETED";

/**
 * NOTE: `android.permission.READ_SMS` is deliberately absent and must stay
 * absent. Google Play prohibits it for expense tracking and shipping it risks
 * removal of the app; bank SMS reach PeraPlano as notifications posted by the
 * device's Messages app, so it would buy nothing either.
 */

/** One `<service>` element, in the xml2js shape the manifest mod works in. */
function listenerServiceElement() {
  return {
    $: {
      "android:name": SERVICE_CLASS,
      // Not addressable from outside the app; the system binds it via the
      // intent-filter action below, which `exported="false"` does not block.
      "android:exported": "false",
      // What the system Notification Access screen shows next to the toggle.
      "android:label": "PeraPlano",
      "android:permission": BIND_PERMISSION,
    },
    "intent-filter": [{ action: [{ $: { "android:name": LISTENER_ACTION } }] }],
  };
}

/**
 * @param {import("expo/config-plugins").AndroidManifest} androidManifest
 * @returns {import("expo/config-plugins").AndroidManifest}
 */
function injectListenerService(androidManifest) {
  const application =
    AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);

  // Appended to whatever is already there -- other libraries contribute
  // services to this same array, and replacing it would strip them.
  const existing = application.service ?? [];

  // IDEMPOTENT BY `android:name`, the only identity Android itself uses. The
  // plugin can legitimately be applied more than once (listed in app.json and
  // picked up again by something else), and a duplicated `<service>` fails the
  // manifest merger at build time.
  const alreadyDeclared = existing.findIndex(
    (service) => service?.$?.["android:name"] === SERVICE_CLASS,
  );

  if (alreadyDeclared === -1) {
    existing.push(listenerServiceElement());
  } else {
    // Rewritten rather than skipped, so a stale element left by an older
    // version of this plugin cannot survive with weaker attributes.
    existing[alreadyDeclared] = listenerServiceElement();
  }

  application.service = existing;

  // `ensurePermission`, not `addPermission`: the latter appends unconditionally
  // and would emit a second `<uses-permission>` on a second application.
  AndroidConfig.Permissions.ensurePermission(androidManifest, BOOT_PERMISSION);

  return androidManifest;
}

/** @type {import("expo/config-plugins").ConfigPlugin} */
const withNotificationListener = (config) =>
  withAndroidManifest(config, (manifestConfig) => {
    manifestConfig.modResults = injectListenerService(manifestConfig.modResults);
    return manifestConfig;
  });

module.exports = withNotificationListener;
